<a href="https://colab.research.google.com/github/sadeenlababneh/homework2-python/blob/main/HomeWorke2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from numpy import random

arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("\n--- Q1 ---")
print("Result:", arr[2, 0])

print("\n--- Q2 ---")
print("Column:", arr[:, 1])

print("\n--- Q3 ---")
print("Type:", arr.dtype)

print("\n--- Q4 ---")
arr_copy = arr.copy()
arr_copy[0, 0] = 100
print("Copy Array:")
print(arr_copy)
print("Original Array:")
print(arr)

print("\n--- Q5 ---")
arr_view = arr.view()
arr_view[0, 0] = 200
print("View Array:")
print(arr_view)
print("Original Array:")
print(arr)

print("\n--- Q6 ---")
print("Shape =", arr.shape)

print("\n--- Q7 ---")
for x in range(arr.shape[0]):
    for y in range(arr.shape[1]):
        print(f"Element at row {x}, column {y} = {arr[x, y]}")


print("\n--- Q8 ---")
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
print("Vertical:")
print(np.vstack((arr, arr2)))
print("Horizontal:")
print(np.hstack((arr, arr2)))

print("\n--- Q9 ---")
print("Split Result:")
for part in np.array_split(arr, 3, axis=1):
    print(part)

print("\n--- Q10 ---")
print("Found at:", np.where(arr == 60))

print("\n--- Q11 ---")
print("Sorted:")
print(np.sort(arr))

print("\n--- Q12 ---")
print("Filtered (>50):", arr[arr > 50])

print("\n--- Q13 ---")
print("Random Array:")
print(random.randint(1, 100, size=(2, 3)))

print("\n--- Q14 ---")
print("Ufunc Result:")
print(np.add(arr, 10))


--- Q1 ---
Result: 70

--- Q2 ---
Column: [20 50 80]

--- Q3 ---
Type: int64

--- Q4 ---
Copy Array:
[[100  20  30]
 [ 40  50  60]
 [ 70  80  90]]
Original Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

--- Q5 ---
View Array:
[[200  20  30]
 [ 40  50  60]
 [ 70  80  90]]
Original Array:
[[200  20  30]
 [ 40  50  60]
 [ 70  80  90]]

--- Q6 ---
Shape = (3, 3)

--- Q7 ---
Element at row 0, column 0 = 200
Element at row 0, column 1 = 20
Element at row 0, column 2 = 30
Element at row 1, column 0 = 40
Element at row 1, column 1 = 50
Element at row 1, column 2 = 60
Element at row 2, column 0 = 70
Element at row 2, column 1 = 80
Element at row 2, column 2 = 90

--- Q8 ---
Vertical:
[[200  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [  1   2   3]
 [  4   5   6]
 [  7   8   9]]
Horizontal:
[[200  20  30   1   2   3]
 [ 40  50  60   4   5   6]
 [ 70  80  90   7   8   9]]

--- Q9 ---
Split Result:
[[200]
 [ 40]
 [ 70]]
[[20]
 [50]
 [80]]
[[30]
 [60]
 [90]]

--- Q10 ---
Found at: (array([1]), array([2])